language: java
before_install:
  - wget http://dl.google.com/android/android-sdk_r18-linux.tgz
  - tar -zxf android-sdk_r18-linux.tgz
  - pwd
  - ( cd ~ && pwd )
  - export ANDROID_HOME=~/build/SeanPONeil/MGoBlog/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --filter 1,2 --no-ui --force --all
  - android update sdk --filter 13 --no-ui --force --all
  - aapt
  - sh get_dependencies.sh